# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-04 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='bank_no',
            new_name='bank_cust',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_no',
            new_name='cart_cust',
        ),
    ]
