# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20161204_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
