# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('Phones', 'phone'), ('Laptops', 'laptop'), ('Men', 'man'), ('Women', 'woman'), ('Laptops', 'laptop'), ('Cars', 'car'), ('Watches', 'watch')], max_length=20),
        ),
    ]
