# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20161206_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
